version: 1.2
tools:
   - subclass: cwl
     primaryDescriptorPath: /tools/Dockstore.cwl
     publish: true
     name: testing
workflows:
   - subclass: cwl
     primaryDescriptorPath: /workflows/HelloWorld.cwl
     publish: true
